/**
 * Copyright 2025 Blackout Secure
 * SPDX-License-Identifier: Apache-2.0
 *
 * Project configuration and branding for the humans.txt generator action.
 * User-editable inputs live in action.yml; this file is strictly for metadata.
 */

const PROJECT_CONFIG = {
  name: 'Humans.txt Generator',
  version: '0.1.0',
  copyrightYearStart: '2025',
  copyrightYearEnd: '2026',
  copyrightHolder: 'Blackout Secure',
  license: 'Apache License 2.0',
  spdxIdentifier: 'Apache-2.0',
  repository: {
    owner: 'blackoutsecure',
    name: 'bos-humanstxt-generator',
    url: 'github.com/blackoutsecure/bos-humanstxt-generator',
    issuesUrl: 'github.com/blackoutsecure/bos-humanstxt-generator/issues',
  },
  brandingEmoji: '👥',
};

function getYearRange() {
  const { copyrightYearStart, copyrightYearEnd } = PROJECT_CONFIG;
  return copyrightYearStart === copyrightYearEnd
    ? copyrightYearStart
    : `${copyrightYearStart}-${copyrightYearEnd}`;
}

function getCopyrightNotice() {
  const { copyrightHolder, license } = PROJECT_CONFIG;
  return `© ${getYearRange()} ${copyrightHolder} | ${license}`;
}

function getProjectTitle() {
  return `${PROJECT_CONFIG.brandingEmoji}  ${PROJECT_CONFIG.name} v${PROJECT_CONFIG.version}`;
}

function getRepositoryUrl() {
  return `Repository: https://${PROJECT_CONFIG.repository.url}`;
}

function getSupportUrl() {
  return `Issues: https://${PROJECT_CONFIG.repository.issuesUrl}`;
}

function getHumansTxtHeader() {
  const { name, version, repository, copyrightHolder, license, spdxIdentifier } = PROJECT_CONFIG;

  return `/* Generated by: ${name} v${version} */
/* Copyright: © ${getYearRange()} ${copyrightHolder} */
/* License: ${license} */
/* SPDX-License-Identifier: ${spdxIdentifier} */
/* Repository: https://${repository.url} */
/* Issues: https://${repository.issuesUrl} */
/*  */
/* humanstxt.org - We are people, not machines */
/* Standard: http://humanstxt.org */
/* Recommended location: /humans.txt */`;
}

module.exports = {
  PROJECT_CONFIG,
  getCopyrightNotice,
  getProjectTitle,
  getRepositoryUrl,
  getSupportUrl,
  getHumansTxtHeader,
};
